files:
  - source: /**/*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        ur-PK: ur-rPK
