files:
  - source: /**/values/*.xml
    translation: /%original_path%-%android_code%/%original_file_name%
    languages_mapping:	
      android_code:	
        af: af
        am: am
        ar: ar
        as: as
        ast-rES: ast-rES
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        cs: cs
        cy: cy
        da: da
        de: de
        el: el
        en-rAU: en-rAU
        en-rCA: en-rCA
        en-rGB: en-rGB
        en-rIN: en-rIN
        eo: eo
        es-rMX: es-rMX
        es-rUS: es-rUS
        es: es
        et: et
        eu: eu
        fa: fa
        fi: fi
        fr-rCA: fr-rCA
        fr: fr
        gd: gd
        gl: gl
        gu: gu
        hi: hi
        hr: hr
        hu: hu
        hy: hy
        in: in
        is: is
        it: it
        iw: iw
        ja: ja
        ka: ka
        kk: kk
        km: km
        kn: kn
        ko: ko
        ku: ku
        ky: ky
        lb: lb
        lo: lo
        lt: lt
        lv: lv
        mk: mk
        ml: ml
        mn: mn
        mr: mr
        ms: ms
        my: my
        nb: nb
        ne: ne
        nl: nl
        or: or
        pa: pa
        pl: pl
        pt-rBR: pt-rBR
        pt-rPT: pt-rPT
        rm: rm
        ro: ro
        ru: ru
        sc-rIT: sc-rIT
        si: si
        sk: sk
        sl: sl
        sq: sq
        sr: sr
        sv: sv
        sw: sw
        ta: ta
        te: te
        th: th
        tl: tl
        tr: tr
        ug: ug
        uk: uk
        ur: ur
        uz: uz
        vi: vi
        zh-rCN: zh-rCN
        zh-rHK: zh-rHK
        zh-rTW: zh-rTW
        zu: zu
    escape_quotes: '2'
